[ui]
label = Dev Health App
is_visible = true

[launcher]
author = Ryan Kershaw-Whittle
version = 1.0.0
description = Dev Splunk app for health monitoring

[install]
state = enabled

[package]
id = dev
name = dev
version = 1.0.0
description = Dev Splunk app

[id]
name = dev
version = 1.0.0
